### ISSUE TITLE
Use API Keys with the API Gateway

### ISSUE THREAD

**Issue by tafs7** [abiglobalhealth/msg-gateway#5]
Need to figure out some way to use api_keys from api-gateway.

Serverless framework provides a way to define your keys to be used by functions like this:

```yaml
provider:
  name: aws
  runtime: nodejs6.10
  apiKeys: # List of API keys to be used by your service API Gateway REST API
    - myFirstKeyName

...

functions:
  myPrivateFunc:
    handler: handler.myprivateFunc
    description: this is a private func that requires an api key
    events:
      - http:
          path: myfunc
          method: post
          private: true
```
