### ISSUE TITLE
Improve handling of secrets

### ISSUE THREAD

**Issue by tafs7** [abiglobalhealth/msg-gateway#6]
We're not handling secrets very well right now. Serverless should be coming out with a built in solution in their final release.

**UPDATE - Oct 2017**
Serverless Framework now allows you to pull parameters from the AWS Parameter Store (SSM) during the deploy by replacing tokens in the yaml config with lookups to the key/value pair stored in the cloud.

Use the AWS CLI to create and store params:
`> aws ssm put-parameter --name MyParam --value Awesome --type "SecureString"` 

Then retrieve them by name from the `serverless.yml` file like this:
```yaml
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    MySuperSecretParam: ${ssm:MyParam~true}
```
Or just use the AWS SDK from the function handlers to retrieve parameters using the SSM client at runtime instead of at deploy time with code.

**OPTIONALLY**
Use a plugin such as `serverless-crypt` or `serverless-kms-secrets`, to just encrypt the secrets at rest using a key generated by AWS KMS, and commit the secrets that way, then decrypt them at deploy time.
